SUPABASE_URL = "https://hbfsezznvshzrgdnlkhu.supabase.co"

SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZnNlenpudnNoenJnZG5sa2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg5MDg2ODIsImV4cCI6MjA5NDQ4NDY4Mn0.Yv2ORu3j8zVwzKiKx9yaRCjBsAl5WUj2EwR3jWbL3Jo"